version: '3'
services:
  app: 
    build: ./app
    volumes:
      - ./app:./app
    ports: 
      - "8000"
      - "27017"
      - "27016"
      - "27015"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"