version: '3'
services:
  app: 
    build:
      context: .
    ports: 
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/site_enabled/app
    depends_on:
      - app
    ports:
      - "80:80"